---
AWSTemplateFormatVersion: "2010-09-09"
Description:
  Creates Methods and Resources for RestApi gateway.

Resources:

  # ride
  Resource01:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !ImportValue apiGatewayRootResourceId
      PathPart: ride
      RestApiId: !ImportValue apiGatewayId

  WildRydesRideOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      RestApiId: !ImportValue apiGatewayId
      ResourceId: !Ref Resource01
      HttpMethod: OPTIONS
      Integration:
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'POST,OPTIONS'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            ResponseTemplates:
              application/json: ''
        PassthroughBehavior: WHEN_NO_MATCH
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        Type: MOCK
      MethodResponses:
        - StatusCode: 200
          ResponseModels:
            application/json: 'Empty'
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: false
            method.response.header.Access-Control-Allow-Methods: false
            method.response.header.Access-Control-Allow-Origin: false

  WildRydesRidePostMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizerId: !ImportValue ApiAuthorizer
      AuthorizationType: COGNITO_USER_POOLS
      HttpMethod: POST
      ResourceId: !Ref Resource01
      RestApiId: !ImportValue apiGatewayId
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri:
          Fn::Join:
            - ':'
            - - 'arn:aws:apigateway'
              - Ref: 'AWS::Region'
              - 'lambda'
              - Fn::Join:
                  - '/'
                  - - 'path'
                    - '2015-03-31'
                    - 'functions'
                    - Fn::ImportValue: UnicornPostLambdaARN
                    - 'invocations'  
# API Deployment
  WildRydesApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      Description: Wild Rydes Api
      RestApiId: !ImportValue apiGatewayId
      StageName: !ImportValue EnvironmentType   

Outputs:
  APIdeploymentURL:
    Value: 
       Fn::Join:
          - ''
          - - 'https://'
            - !ImportValue apiGatewayId
            - '.execute-api.'
            - !Ref 'AWS::Region'
            - '.amazonaws.com'
            - "/" 
            - !ImportValue EnvironmentType
    Export:
      Name: APIdeploymentURL  