---
AWSTemplateFormatVersion: "2010-09-09"

Description:
  Creates a static website using S3 for serverless web application

Parameters:
  BucketName:
    Type: String
    Default: sapp
    Description: The name for the bucket hosting your website.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Website Configuration"
        Parameters:
          - BucketName

Resources:

  WebsiteBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Join [ '-', [ !ImportValue ProjectID, !ImportValue EnvironmentType, !Ref BucketName] ]
      WebsiteConfiguration:
        IndexDocument: index.html

  WebsiteBucketPolicy:
    Type: "AWS::S3::BucketPolicy"  
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub "arn:aws:s3:::${WebsiteBucket}/*"
               
  CleanupArtifactBucketOnDelete:
    Type: Custom::cleanupbucket
    Properties:
      ServiceToken: !ImportValue EmptyS3OnDeleteLambdaARN
      BucketName: !Ref WebsiteBucket       
          
Outputs:
  WebsiteURL:
    Value: !GetAtt WebsiteBucket.WebsiteURL
    
  # WebsiteBucketARN:
    # Value:
       # Fn::GetAtt: 
          # - "WebsiteBucket"
          # - "Arn"    
    # Export:
      # Name: WebsiteBucketARN
      
  WebsiteBucketName:
    Value: !Ref WebsiteBucket    
    Export:
      Name: WebsiteBucketName        